### ISSUE TITLE
Upload Docker images

### ISSUE THREAD

**Issue by mrakitin** [NSLS-II/conda-pack-template#15]
Implement automated uploading of the resulting Docker images to:
- [ ] DockerHub: https://hub.docker.com
- [ ] GitHub Container Registry: https://github.com/orgs/NSLS-II/packages/docker

xref: the second task from https://github.com/NSLS-II/conda-pack-template/pull/9.

**Comment by mrakitin** [comment]
The docs that will help us accomplish it: https://docs.github.com/en/actions/guides/publishing-docker-images.

**Comment by johngedell** [comment]
Successfully completed several days ago.
