### ISSUE TITLE
Zenodo upload to the existing deposition

### ISSUE THREAD

**Issue by mrakitin** [NSLS-II/conda-pack-template#26]
As mentioned in https://github.com/NSLS-II/conda-pack-template/pull/17#pullrequestreview-728852281, we need to update the code so that it can upload to the existing deposition when a new version of an environment is generated.

Checklist:
- [x] a link to the deposition that was automatically created via CI that contains a new version of `n2sn` v0.3.7.

**Comment by johngedell** [comment]
https://sandbox.zenodo.org/record/898631

The added code will check to see if the new version is in Zenodo. If not, it creates a new record and uploads the files with the new version. I have not figured out a way to add it to an existing deposition through the API (if it is possible).

**Comment by mrakitin** [comment]
How https://sandbox.zenodo.org/record/898631 was created? Manually or via your code?

**Comment by johngedell** [comment]
The record: https://sandbox.zenodo.org/record/898631 was created via my code.
