### ISSUE TITLE
Format a table with found depositions with `tabulate`

### ISSUE THREAD

**Issue by mrakitin** [NSLS-II/conda-pack-template#27]
The following code can be reworked to use the [`tabulate`](https://github.com/astanin/python-tabulate) library to have a nice table with the results:
https://github.com/NSLS-II/conda-pack-template/blob/31045f9954cf5d77a4002b95cfeb6bcc3a24d434/zenodo_uploader.py#L57-L78

Right now it looks like:
![image](https://user-images.githubusercontent.com/13209176/129236986-def4e5b1-2a7c-4b5c-b22d-93484f9b1c9a.png)

Checklist:
- [x] table is formatted with `tabulate`
- [x] an example snapshot is posted here and/or in the associated PR in the comment
- [x] optionally, add the date of the found depositions

**Comment by johngedell** [comment]
New table:

![table_v2](https://user-images.githubusercontent.com/74158598/129309100-a921a522-f75a-49f7-8e5c-55584e8f5f6b.PNG)

I got carried away when I was programming the other part and completely forgot that there was already code created for this.

I will incorporate that code and make the changes tomorrow.

**Comment by mrakitin** [comment]
Thanks, not bad!

Please use the function from https://github.com/mrakitin/profile_zenodo/blob/master/startup/00-base.py (with minor modifications on your end).

**Comment by johngedell** [comment]
Completed.
